runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /logo
  static_dir: logo
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app
- url: "/notes"
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
