runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles/.*
  script: static_dir
- url: /scripts/.*
  script: static_dir
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
